{{- if .Values.deployment.enabled }}
{{- $fullName := include "common.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
      {{- with .Values.selectorLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
        {{- with .Values.selectorLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.deployment.initContainers }}
      initContainers:
        {{- range .Values.deployment.initContainers }}
        - name: {{ .name }}
          image: {{ .image }}
          {{- if .command }}
          command:
            {{- toYaml .command | nindent 12 }}
          {{- end }}
          {{- if .restartPolicy }}
          restartPolicy: {{ .restartPolicy }}
          {{- end }}
          {{- if .args }}
          args:
            {{- toYaml .args | nindent 12 }}
          {{- end }}
          {{- if .env }}
          env:
            {{- range $k, $v := .env }}
            - name: {{ $k | quote }}
            {{- if eq $v.type "kv" }}
              value: {{ $v.value | quote }}
            {{- else if or (eq $v.type "parameterStore") (eq $v.type "secretsManager") }}
              valueFrom:
                secretKeyRef:
                  name: "{{ $fullName }}-{{ $v.name }}"
                  key: "{{ $fullName }}-{{ $v.name }}"
            {{- else if eq $v.type "configmapRef" }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $v.name | quote }}
                  key: {{ $v.key | quote }}
            {{- end }}
            {{- end }}
          {{- end }}
          {{- if .volumeMounts }}
          volumeMounts:
            {{- range $mount := .volumeMounts }}
            - name: {{ $mount.name }}
              mountPath: {{ $mount.mountPath }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "common.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.deployment.volumes }}
      volumes:
        {{- range $volume := .Values.deployment.volumes }}
        {{- if eq $volume.type "pvc" }}
        - name: {{ $fullName }}-{{ $volume.name }}-volume
          persistentVolumeClaim:
            claimName: {{ $fullName }}-{{ $volume.name }}-pvc
        {{- else if or (eq $volume.type "secret") (eq $volume.type "secretsManager") }}
        - name: {{ $volume.name }}
          secret:
            secretName: {{ $volume.secretName | quote }}
            defaultMode: {{ $volume.defaultMode | default 420 }}
            {{- if $volume.filePath }}
            items:
              - key: {{ $volume.secretName | quote }}
                path: {{ $volume.filePath }}
            {{- end }}
        {{- else if eq $volume.type "configMap" }}
        - name: {{ $volume.name }}
          configMap:
            name: {{ $volume.configMapName | quote }}
            defaultMode: {{ $volume.defaultMode | default 420 }}
        {{- else if eq $volume.type "emptyDir" }}
        - name: {{ $volume.name }}
          emptyDir: {}
        {{- end }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ include "common.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.deployment.volumes }}
          volumeMounts:
            {{- range $volume := .Values.deployment.volumes }}
            {{- if eq $volume.type "pvc" }}
            - name: {{ $fullName }}-{{ $volume.name }}-volume
              mountPath: {{ $volume.mountPath }}
            {{- else }}
            - name: {{ $volume.name }}
              mountPath: {{ $volume.mountPath }}
              {{- if $volume.subPath }}
              subPath: {{ $volume.subPath }}
              {{- end }}
              {{- if $volume.readOnly }}
              readOnly: {{ $volume.readOnly }}
              {{- end }}
            {{- end }}
            {{- end }}
          {{- end }}
          {{- if .Values.command }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          {{- end }}
          {{- if .Values.args }}
          args:
            {{- toYaml .Values.args | nindent 12 }}
          {{- end }}
          {{- if .Values.service.containerPort }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          {{- else if .Values.deployment.ports }} # If ports are defined for the deployment, use all of them
          ports:
            {{- range .Values.deployment.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol | default "TCP" }}
            {{- end }}
          {{- end }}
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k | quote }}
            {{- if eq $v.type "kv" }}
              value: {{ $v.value | quote }}
            {{- else if or (eq $v.type "parameterStore") (eq $v.type "secretsManager") }}
              valueFrom:
                secretKeyRef:
                  name: "{{ $fullName }}-{{ $v.name }}"
                  key: "{{ $fullName }}-{{ $v.name }}"
            {{- else if eq $v.type "configmapRef" }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $v.name | quote }}
                  key: {{ $v.key | quote }}
            {{- end }}
            {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

        {{- if .Values.sidecars }}
        {{- range .Values.sidecars }}
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy | default "IfNotPresent" }}
          {{- if .volumeMounts }}
          volumeMounts:
            {{- range .volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
          {{- end }}
          {{- if .ports }}
          ports:
            {{- range .ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol | default "TCP" }}
            {{- end }}
          {{- end }}
          {{- if .args }}
          args:
            {{- toYaml .args | nindent 12 }}
          {{- end }}
          {{- if .env }}
          env:
            {{- range $k, $v := .env }}
            - name: {{ $k | quote }}
              {{- if eq $v.type "kv" }}
              value: {{ $v.value | quote }}
              {{- else if or (eq $v.type "parameterStore") (eq $v.type "secretsManager") }}
              valueFrom:
                secretKeyRef:
                  name: "{{ $fullName }}-{{ $v.name }}"
                  key: "{{ $fullName }}-{{ $v.name }}"
              {{- else if eq $v.type "configmapRef" }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $v.name | quote }}
                  key: {{ $v.key | quote }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- if .resources }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
