{{- $fullName := include "common.fullname" . -}}
{{ $externalSecrets := default dict .Values.externalSecrets }}
{{- range $k, $v := .Values.env }}
---
{{- if or (eq $v.type "parameterStore") (eq $v.type "secretsManager") }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ $fullName }}-{{ $v.name }}"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $externalSecrets.clusterSecretStoreName }}
  data:
    - secretKey: "{{ $fullName }}-{{ $v.name }}"
      remoteRef:
        key: {{ if eq $v.type "secretsManager" }}{{ $v.secret_name }}{{ else }}{{ $v.parameter_name }}{{ end }}
{{- end }}
{{- end }}
