{{- $volumes := concat (.Values.deployment.volumes | default list) (.Values.statefulset.volumes | default list) -}}
{{- if $volumes }}
{{- $fullName := include "common.fullname" . -}}
{{- range $volume := $volumes }}
{{- if eq $volume.type "pvc" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}-{{ $volume.name }}-pvc
  {{- with $volume.annotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  {{- with $volume.accessModes }}
  accessModes:
  {{ toYaml . | indent 4 }}
  {{- end }}
  {{- if $volume.storageClass }}
    {{- if eq $volume.storageClass "-" }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ $volume.storageClass }}
    {{- end }}
  {{- else }}
  storageClassName: {{ $fullName }}-{{ $volume.name }}-sc
  {{- end }}
  {{- if $volume.resources }}
  resources:
    {{- toYaml $volume.resources | nindent 4 }}
  {{- end }}
  {{- if $volume.volumeName }}
  volumeName: {{ $volume.volumeName }}
  {{ - else }}
  volumeName: {{ $fullName }}-{{ $volume.name }}-pvc
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
